FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY backend/DriftingLeaves.jar app.jar

EXPOSE 5922

ENV TZ=Asia/Shanghai
ENV JAVA_OPTS="-Xms512m -Xmx1024m"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
